version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    networks:
      - mern-networks
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:4000"    # host:container mapping
    environment:
      - PORT=4000      # container internal port, must match backend app listen port
      - MONGO_URL=mongodb://mongo:27017/InsuranceDekho
      - JWT_SECRET=jwt_secret
      - RAZORPAY_KEY_ID=rzp_test_enSNChz4e2UlQM
      - RAZORPAY_KEY_SECRET=dTCBH71HGxDxprdMYwYMaMHP
      - MONGO_URI=mongodb://mongo:27017/insurancedb

    networks:
      - mern-networks
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:4000   # Docker service name + container port
    depends_on:
      - backend
    networks:
      - mern-networks
    restart: always
