version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "5000:4000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/InsuranceDekho
      - JWT_SECRET=jwt_secret
      - RAZORPAY_KEY_ID=rzp_test_enSNChz4e2UlQM
      - RAZORPAY_KEY_SECRET=dTCBH71HGxDxprdMYwYMaMHP
      - MONGO_URI=mongodb://mongo:27017/insurancedb
      - PUBLIC_IP=${PUBLIC_IP}  # Add this

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://${PUBLIC_IP}:5000
    depends_on:
      - backend
