version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    image: insurance-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    image: insurance-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
