version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    networks:
      - mern-networks
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
      - ./backend/.env
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
    depends_on:
      - mongo
    networks:
      - mern-networks
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        PUBLIC_IP: ${PUBLIC_IP}
        REACT_APP_API_URL: http://${PUBLIC_IP}:5000
        REACT_APP_RAZORPAY_KEY_ID: rzp_test_enSNChz4e2UlQM
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-networks
    restart: always
    env_file:
      - .env

networks:
  mern-networks:
    driver: bridge
