services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      mern-networks:
        aliases:
          - mongo
    restart: always

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
    depends_on:
      - mongo
    networks:
      mern-networks:
        aliases:
          - backend
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://backend:4000"  # Using service name for internal communication
        REACT_APP_RAZORPAY_KEY_ID: "rzp_test_enSNChz4e2UlQM"
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      mern-networks:
        aliases:
          - frontend
    restart: always

networks:
  mern-networks:
    driver: bridge

volumes:
  mongo-data: